server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://119.29.130.179:3306/baba_circle?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root99
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      connection-timeout: 50000
      maximum-pool-size: 60
      minimum-idle: 10
  rabbitmq:
    host: 119.29.130.179
    port: 5672
    username: admin
    password: admin
    connection-timeout: 60s
    listener:
      direct:
        acknowledge-mode: none
  redis:
    host: 119.29.130.179
    timeout: 5000
    jedis:
      pool:
        max-wait: 1000
        max-active: 20
        min-idle: 1
  # 设置单个文件最大上传大小和总文件上传大小
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:com/example/babacirclecommunity/*/dao/mapper/*.xml
  #配置别名
  type-aliases-package: com.example.babacirclecommunity.*.entity
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
app:
  workerId: 1
  dataCenterId: 2
